apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: datasciencepipelinesapplications-controller
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: data-science-pipelines-operator
    app.kubernetes.io/part-of: data-science-pipelines-operator
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 3
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      volumes:
        - name: config
          configMap:
            name: dspo-config
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        - --config
        - /home/config
        image: controller:latest
        name: manager
        env:
          - name: IMAGES_APISERVER
            value: quay.io/modh/odh-ml-pipelines-api-server-container:v1.18.0-8
          - name: IMAGES_ARTIFACT
            value: quay.io/modh/odh-ml-pipelines-artifact-manager-container:v1.18.0-8
          - name: IMAGES_PERSISTENTAGENT
            value: quay.io/modh/odh-ml-pipelines-persistenceagent-container:v1.18.0-8
          - name: IMAGES_SCHEDULEDWORKFLOW
            value: quay.io/modh/odh-ml-pipelines-scheduledworkflow-container:v1.18.0-8
          - name: IMAGES_VIEWERCRD
            value: quay.io/modh/odh-ml-pipelines-viewercontroller-container:v1.18.0-8
          - name: IMAGES_CACHE
            value: registry.access.redhat.com/ubi8/ubi-minimal
          - name: IMAGES_MOVERESULTSIMAGE
            value: busybox
          - name: IMAGES_MLPIPELINEUI
            value: quay.io/opendatahub/odh-ml-pipelines-frontend-container:beta-ui
          - name: IMAGES_MARIADB
            value: registry.redhat.io/rhel8/mariadb-103:1-188
          - name: IMAGES_MINIO
            value: quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 2Gi
        volumeMounts:
          - mountPath: /home/config
            name: config
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
