apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-grpc-configmap
  labels:
    component: metadata-grpc-server
data:
  METADATA_GRPC_SERVICE_HOST: "ds-pipeline-metadata-grpc-sample.kubeflow.svc.cluster.local"
  METADATA_GRPC_SERVICE_PORT: "8080"