apiVersion: v1
data:
  artifactRepository: |
    archiveLogs: false
    s3:
      endpoint: "http://minio-sample.kubeflow.svc.cluster.local:9000"
      bucket: "mlpipeline"
      insecure: false
      accessKeySecret:
        name: "mlpipeline-minio-artifact"
        key: "accesskey"
      secretKeySecret:
        name: "mlpipeline-minio-artifact"
        key: "secretkey"
  containerRuntimeExecutor: emissary
  executor: |
    imagePullPolicy: IfNotPresent
kind: ConfigMap
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|workflow-controller-configmap'
  name: workflow-controller-configmap
