apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../argo
namespace: redhat-ods-applications

vars:
  - name: IMAGES_ARGO_SERVER
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_ARGO_SERVER

configMapGenerator:
  - name: dspo-parameters
    behavior: merge
    envs:
      - params.env
