apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opendatahub
resources:
- ../../base
patchesStrategicMerge:
- img_patch.yaml
images:
- name: controller
  newName: quay.io/hukhan/data-science-pipelines-operator
  newTag: RHOAIENG-1690-2385-2
